#include "Stdafx.h"
#include "Resources.h"

HRESULT Resources::init(void)
{
	IMAGEMANAGER->addImage("TitleBG", "Resources/Images/BackGrounds/TitleScene/TitleBG.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("TitleName", "Resources/Images/BackGrounds/TitleScene/TitleName.bmp", 451, 117, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("TitleEFX2", "Resources/Images/Effects/TitleScene/TitleEFX2.bmp", 2241, 2025, 6, 6, true, RGB(4, 0, 4));
	IMAGEMANAGER->addFrameImage("TitleEFX1", "Resources/Images/Effects/TitleScene/TitleEFX1.bmp", 3315, 2398, 13, 11, true, RGB(4, 100, 4));
	IMAGEMANAGER->addFrameImage("TitleButtons", "Resources/Images/BackGrounds/TitleScene/TitleButtons.bmp", 390, 124, 2, 4, true, RGB(252, 0, 0));

	IMAGEMANAGER->addImage("ScenarioBG", "Resources/Images/BackGrounds/ScenarioScene/Scenario_BG.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addFrameImage("Scenarios", "Resources/Images/BackGrounds/ScenarioScene/Scenarios.bmp", 1680, 2700, 6, 27, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("ScrollUp", "Resources/Images/BackGrounds/ScenarioScene/ScrollUp.bmp", 19, 45, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("ScrollDown", "Resources/Images/BackGrounds/ScenarioScene/ScrollDown.bmp", 19, 45, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("ScrollNoClick", "Resources/Images/BackGrounds/ScenarioScene/ScrollNoClick.bmp", 15, 43, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("ScrollClick", "Resources/Images/BackGrounds/ScenarioScene/ScrollClick.bmp", 15, 43, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("WorldMap", "Resources/Images/BackGrounds/WorldMapScene/WorldMap.bmp", 1347, 839);

	IMAGEMANAGER->addImage("TextBox", "Resources/Images/UI/TextBox.bmp", 230, 105);
	IMAGEMANAGER->addImage("ShopTitle", "Resources/Images/UI/ShopTitle.bmp", 620, 49);
	IMAGEMANAGER->addImage("ShopTitleLT", "Resources/Images/UI/ShopTitleLT.bmp", 80, 13, true, RGB(252, 252, 252));
	IMAGEMANAGER->addImage("ShopTitleRB", "Resources/Images/UI/ShopTitleRB.bmp", 80, 13, true, RGB(252, 252, 252));
	IMAGEMANAGER->addImage("ShopButton", "Resources/Images/UI/ShopButton.bmp", 140, 36);
	IMAGEMANAGER->addImage("Empty", "Resources/Images/UI/Empty.bmp", 50, 50);
	IMAGEMANAGER->addImage("없음", "Resources/Images/UI/Shop/없음.bmp", 24, 24);
	IMAGEMANAGER->addImage("PressButton", "Resources/Images/UI/PressButton.bmp", 140, 36);
	IMAGEMANAGER->addFrameImage("ShopIcon", "Resources/Images/UI/ShopIcon.bmp", 140, 35, 4, 1, true, RGB(236, 208, 208));
	IMAGEMANAGER->addImage("ShopButtonActive", "Resources/Images/UI/ShopButtonActive.bmp", 140, 36);
	IMAGEMANAGER->addImage("MapCoordination", "Resources/Images/UI/MapCoordination.bmp", 70, 38);
	IMAGEMANAGER->addImage("EldBar", "Resources/Images/UI/EldBar.bmp", 62, 4);
	IMAGEMANAGER->addImage("EldIcon", "Resources/Images/UI/EldIcon.bmp", 12, 15, true, RGB(252, 252, 252));
	IMAGEMANAGER->addImage("CurEld", "Resources/Images/UI/CurEld.bmp", 7, 6, true, RGB(252, 252, 252));
	IMAGEMANAGER->addImage("DialogVermont", "Resources/Images/UI/Vermont.bmp", 260, 480, true, RGB(0, 0, 4));
	IMAGEMANAGER->addImage("DialogSaladin", "Resources/Images/UI/Saladin.bmp", 400, 480, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("DialogSherazade", "Resources/Images/UI/Sherazade.bmp", 424, 480, true, RGB(255, 0, 255 ));
	IMAGEMANAGER->addImage("HpBar", "Resources/Images/UI/HpBar.bmp", 2, 12);
	IMAGEMANAGER->addImage("MpBar", "Resources/Images/UI/MpBar.bmp", 2, 12);
	IMAGEMANAGER->addImage("StatusBar", "Resources/Images/UI/StatusBar.bmp", 150, 3);
	IMAGEMANAGER->addImage("StatusHpBar", "Resources/Images/UI/StatusHpBar.bmp", 150, 3);
	IMAGEMANAGER->addImage("StatusSoulBar", "Resources/Images/UI/StatusSoulBar.bmp", 150, 3);
	IMAGEMANAGER->addImage("StatusExpBar", "Resources/Images/UI/StatusExpBar.bmp", 150, 3);
	IMAGEMANAGER->addImage("StatusButton", "Resources/Images/UI/StatusButton.bmp", 130, 24, true, RGB(252, 252, 252));
	IMAGEMANAGER->addFrameImage("ForeheadKiss", "Resources/Images/BackGrounds/EndingScene/ForeheadKiss.bmp", 432, 79, 6, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("VermontEnding", "Resources/Images/BackGrounds/EndingScene/VermontEnding.bmp", 130, 78, 2, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("SaladinEnding", "Resources/Images/BackGrounds/EndingScene/SaladinEnding.bmp", 1208, 101, 8, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("EndingBG", "Resources/Images/BackGrounds/EndingScene/EndingBG.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("LoadBG", "Resources/Images/BackGrounds/TitleScene/LoadBG.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Reminisce1", "Resources/Images/BackGrounds/EndingScene/Reminisce1.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Reminisce2", "Resources/Images/BackGrounds/EndingScene/Reminisce2.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Reminisce3", "Resources/Images/BackGrounds/EndingScene/Reminisce3.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Reminisce4", "Resources/Images/BackGrounds/EndingScene/Reminisce4.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Reminisce5", "Resources/Images/BackGrounds/EndingScene/Reminisce5.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Reminisce6", "Resources/Images/BackGrounds/EndingScene/Reminisce6.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Reminisce7", "Resources/Images/BackGrounds/EndingScene/Reminisce7.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Reveal", "Resources/Images/BackGrounds/EndingScene/Reveal.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Brother", "Resources/Images/BackGrounds/EndingScene/Brother.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Subtitle1", "Resources/Images/BackGrounds/EndingScene/Subtitle1.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Subtitle2", "Resources/Images/BackGrounds/EndingScene/Subtitle2.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Subtitle3", "Resources/Images/BackGrounds/EndingScene/Subtitle3.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Subtitle4", "Resources/Images/BackGrounds/EndingScene/Subtitle4.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("PlaySong", "Resources/Images/BackGrounds/EndingScene/PlaySong.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Black", "Resources/Images/BackGrounds/EndingScene/Black.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("White", "Resources/Images/BackGrounds/EndingScene/White.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("Blue", "Resources/Images/Effects/SkillEffect/Blue.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addFrameImage("Pipe", "Resources/Images/BackGrounds/EndingScene/Pipe.bmp", 20, 10, 2, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("SlashRight", "Resources/Images/BackGrounds/EndingScene/SlashRight.bmp", 785, 150, 5, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("MouseCursor", "Resources/Images/UI/MouseCursor.bmp", 112, 24, 7, 1, true, RGB(80, 120, 116));
	IMAGEMANAGER->addFrameImage("AttackMouseCursor", "Resources/Images/UI/AttackMouseCursor.bmp", 217, 32, 7, 1, true, RGB(80, 120, 116));
	IMAGEMANAGER->addFrameImage("EnemyMiniStatus", "Resources/Images/UI/EnemyMiniStatus.bmp", 900, 49, 15, 1, true, RGB(0, 44, 0));
	IMAGEMANAGER->addFrameImage("PlayerMiniStatus", "Resources/Images/UI/PlayerMiniStatus.bmp", 900, 49, 15, 1, true, RGB(0, 44, 0));
	IMAGEMANAGER->addFrameImage("TitleEFX4", "Resources/Images/Effects/TitleScene/TitleEFX4.bmp", 4080, 254, 16, 1, true, RGB(4, 0, 4));
	IMAGEMANAGER->addImage("test", "Resources/Images/Effects/StoryScene/test2.bmp", 201, 242, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("TitleEFX3", "Resources/Images/Effects/TitleScene/TitleEFX3.bmp", 20880, 240, 87, 1, true, RGB(4, 88, 4));

	// 전투맵 이미지
	IMAGEMANAGER->addImage("BossBattleBG", "Resources/Images/BackGrounds/BossBattleScene/BossBattleBG.bmp", 1600, 1800);
	IMAGEMANAGER->addImage("BattleSceneBG1", "Resources/Images/BackGrounds/BattleScene/BattleSceneBG1.bmp", 1080, 1920);
	IMAGEMANAGER->addImage("검사용BattleSceneBG1", "Resources/Images/BackGrounds/BattleScene/검사용BattleSceneBG1.bmp", 1200, 1920);
	IMAGEMANAGER->addImage("Object1-1", "Resources/Images/BackGrounds/BattleScene/Object1-1.bmp", 360, 208, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-2", "Resources/Images/BackGrounds/BattleScene/Object1-2.bmp", 360, 176, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-3", "Resources/Images/BackGrounds/BattleScene/Object1-3.bmp", 360, 432, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-4", "Resources/Images/BackGrounds/BattleScene/Object1-4.bmp", 280, 432, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-5", "Resources/Images/BackGrounds/BattleScene/Object1-5.bmp", 160, 96, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-6", "Resources/Images/BackGrounds/BattleScene/Object1-6.bmp", 360, 104, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-7", "Resources/Images/BackGrounds/BattleScene/Object1-7.bmp", 280, 104, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-8", "Resources/Images/BackGrounds/BattleScene/Object1-8.bmp", 120, 184, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-9", "Resources/Images/BackGrounds/BattleScene/Object1-9.bmp", 160, 184, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-10", "Resources/Images/BackGrounds/BattleScene/Object1-10.bmp", 40, 192, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object1-11", "Resources/Images/BackGrounds/BattleScene/Object1-11.bmp", 40, 192, true, RGB(0, 0, 0));

	IMAGEMANAGER->addImage("BattleSceneBG3", "Resources/Images/BackGrounds/BattleScene/BattleSceneBG3.bmp", 1600, 1290);
	IMAGEMANAGER->addImage("검사용BattleSceneBG3", "Resources/Images/BackGrounds/BattleScene/검사용BattleSceneBG3.bmp", 1600, 1290);
	IMAGEMANAGER->addImage("Object3-1", "Resources/Images/BackGrounds/BattleScene/Object3-1.bmp", 80, 440, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object3-2", "Resources/Images/BackGrounds/BattleScene/Object3-2.bmp", 80, 440, true, RGB(0, 0, 0));

	IMAGEMANAGER->addImage("BattleSceneBG4", "Resources/Images/BackGrounds/BattleScene/BattleSceneBG4.bmp",1400, 1920);
	IMAGEMANAGER->addImage("검사용BattleSceneBG4", "Resources/Images/BackGrounds/BattleScene/검사용BattleSceneBG4.bmp", 1400, 1920);
	IMAGEMANAGER->addImage("Object4-1", "Resources/Images/BackGrounds/BattleScene/Object4-1.bmp", 400, 320, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object4-2", "Resources/Images/BackGrounds/BattleScene/Object4-2.bmp", 320, 272, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object4-3", "Resources/Images/BackGrounds/BattleScene/Object4-3.bmp", 600, 184, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object4-4", "Resources/Images/BackGrounds/BattleScene/Object4-4.bmp", 120, 104, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object4-5", "Resources/Images/BackGrounds/BattleScene/Object4-5.bmp", 600, 272, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object4-6", "Resources/Images/BackGrounds/BattleScene/Object4-6.bmp", 600, 240, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Object4-7", "Resources/Images/BackGrounds/BattleScene/Object4-7.bmp", 40, 272, true, RGB(0, 0, 0));


	IMAGEMANAGER->addImage("Table", "Resources/Images/BackGrounds/BossBattleScene/Table.bmp", 120, 136, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("SaladinIdleLeft", "Resources/Images/Characters/Saladin/SaladinIdleLeft.bmp", 272, 90, 4, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("SaladinIdleRight", "Resources/Images/Characters/Saladin/SaladinIdleRight.bmp", 272, 90, 4, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("SaladinIdleUp", "Resources/Images/Characters/Saladin/SaladinIdleUp.bmp", 280, 90, 4, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("SaladinIdleDown", "Resources/Images/Characters/Saladin/SaladinIdleDown.bmp", 280, 90, 4, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("SaladinAttackUp", "Resources/Images/Characters/Saladin/SaladinAttackUp.bmp", 648, 138, 6, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("SaladinAttackSide", "Resources/Images/Characters/Saladin/SaladinAttackSide.bmp", 790, 176, 5, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("SaladinAttackDown", "Resources/Images/Characters/Saladin/SaladinAttackDown.bmp", 505, 116, 5, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("SaladinMove", "Resources/Images/Characters/Saladin/SaladinMove.bmp", 720, 480, 6, 4, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("CursorTile", "Resources/Images/UI/CursorTile.bmp", 240, 32, 6, 1);
	IMAGEMANAGER->addFrameImage("CantMoveTile", "Resources/Images/UI/CantMoveTile.bmp", 76, 42, 2, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("MovableTile", "Resources/Images/UI/MovableTile.bmp", 40, 32);
	IMAGEMANAGER->addImage("AttackableTile", "Resources/Images/UI/AttackableTile.bmp", 40, 32);
	IMAGEMANAGER->addImage("SkillableTile", "Resources/Images/UI/SkillableTile.bmp", 40, 32);
	IMAGEMANAGER->addImage("ActionButton", "Resources/Images/UI/ActionButton.bmp", 102, 28, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("ActionButtonActive", "Resources/Images/UI/ActionButtonActive.bmp", 102, 28, true, RGB(255, 45, 254));
	IMAGEMANAGER->addImage("SkillIcon", "Resources/Images/UI/SkillIcon.bmp", 17, 17, true, RGB(252, 236, 248));
	IMAGEMANAGER->addImage("SkillButtonActive", "Resources/Images/UI/SkillButtonActive.bmp", 80, 22);
	IMAGEMANAGER->addImage("WorldMapInfo", "Resources/Images/UI/WorldMapInfo.bmp", 241, 111, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("WorldMapFlag", "Resources/Images/UI/WorldMapFlag.bmp", 61, 91, true, RGB(252, 252, 252));
	IMAGEMANAGER->addImage("WorldMapSaladin", "Resources/Images/UI/WorldMapSaladin.bmp", 50, 50);
	IMAGEMANAGER->addImage("살라딘Mini", "Resources/Images/UI/SaladinMini.bmp", 50, 50);
	IMAGEMANAGER->addImage("철가면Mini", "Resources/Images/UI/IronMaskMini.bmp", 50, 50);
	IMAGEMANAGER->addFrameImage("ActionIcon", "Resources/Images/UI/ActionIcon.bmp", 96, 25, 4, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("WorldMapMoveMarker", "Resources/Images/UI/WorldMapMoveMarker.bmp", 3360, 120, 28, 1, true, RGB(255, 45, 254));
	IMAGEMANAGER->addFrameImage("MiniStatusWindow", "Resources/Images/UI/MiniStatusWindow.bmp", 900, 49, 15, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("WorldMapMarker", "Resources/Images/UI/WorldMapMarker.bmp", 1120, 120, 10, 1, true, RGB(0, 252, 0));
	IMAGEMANAGER->addImage("SaladinMark", "Resources/Images/UI/SaladinMark3.bmp", 41, 54, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("EnemyMarker", "Resources/Images/UI/EnemyMarker.bmp", 72, 11, 8, 1, true, RGB(80, 120, 116));
	IMAGEMANAGER->addFrameImage("PlayerMarker", "Resources/Images/UI/PlayerMarker.bmp", 72, 11, 8, 1, true, RGB(80, 120, 116));
	IMAGEMANAGER->addFrameImage("WorldMapTeam", "Resources/Images/UI/WorldMapTeam.bmp", 195, 18, 5, 1);
	IMAGEMANAGER->addFrameImage("VermontSherazade", "Resources/Images/BackGrounds/StoryScene/VermontSherazade.bmp", 3816, 90, 24, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("Red", "Resources/Images/BackGrounds/StoryScene/RedBG.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("ShopSceneBG", "Resources/Images/BackGrounds/ShopScene/ShopSceneBG.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("AbandonedSwords", "Resources/Images/BackGrounds/StoryScene/AbandonedSwods.bmp", 55, 45, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("Soldier1", "Resources/Images/BackGrounds/StoryScene/Soldier1.bmp", 58, 67, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier2", "Resources/Images/BackGrounds/StoryScene/Soldier2.bmp", 54, 69, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier3", "Resources/Images/BackGrounds/StoryScene/Soldier3.bmp", 55, 65, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier4", "Resources/Images/BackGrounds/StoryScene/Soldier4.bmp", 47, 76, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("SaladinStory", "Resources/Images/BackGrounds/StoryScene/SaladinStory.bmp", 260, 75, 4, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Enemy", "Resources/Images/Characters/Enemy.bmp", 516, 848, 6, 8, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Nakama", "Resources/Images/Characters/Nakama.bmp", 516, 752, 6, 8, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("VermontMoveLeft", "Resources/Images/Characters/Vermont/VermontMoveLeft.bmp", 462, 76, 6, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontMoveRight", "Resources/Images/Characters/Vermont/VermontMoveRight.bmp", 462, 76, 6, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontMoveUp", "Resources/Images/Characters/Vermont/VermontMoveUp.bmp", 228, 80, 6, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontMoveDown", "Resources/Images/Characters/Vermont/VermontMoveDown.bmp", 372, 91, 6, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontIdleLeft", "Resources/Images/Characters/Vermont/VermontIdleLeft.bmp", 185, 75, 5, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontIdleRight", "Resources/Images/Characters/Vermont/VermontIdleRight.bmp", 185, 75, 5, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontIdleUp", "Resources/Images/Characters/Vermont/VermontIdleUp.bmp", 265, 87, 5, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontIdleDown", "Resources/Images/Characters/Vermont/VermontIdleDown.bmp", 245, 78, 5, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontAttackLeft", "Resources/Images/Characters/Vermont/VermontAttackLeft.bmp", 452, 118, 4, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontAttackRight", "Resources/Images/Characters/Vermont/VermontAttackRight.bmp", 452, 118, 4, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontAttackSideEffect", "Resources/Images/Effects/SkillEffect/VermontAttackSideEffect.bmp", 636, 166, 4, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("VermontAttackUpEffect", "Resources/Images/Effects/SkillEffect/VermontAttackUpEffect.bmp", 548, 119, 4, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("VermontAttackDownEffect", "Resources/Images/Effects/SkillEffect/VermontAttackDownEffect.bmp", 512, 132, 4, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Wolf", "Resources/Images/Effects/SkillEffect/혈랑마혼/Wolf.bmp", 5278, 199, 26, 1, true, RGB(100, 0, 4));
	IMAGEMANAGER->addFrameImage("Spark", "Resources/Images/Effects/SkillEffect/혈랑마혼/Spark.bmp", 1845, 137, 15, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Thunder", "Resources/Images/Effects/SkillEffect/혈랑마혼/Thunder.bmp", 384, 255, 6, 1, true, RGB(0, 0, 4));
	IMAGEMANAGER->addImage("VermontDamagedLeft", "Resources/Images/Characters/Vermont/VermontDamagedLeft.bmp", 65, 69, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("VermontDamagedRight", "Resources/Images/Characters/Vermont/VermontDamagedRight.bmp", 65, 69, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("VermontDamagedUp", "Resources/Images/Characters/Vermont/VermontDamagedUp.bmp", 47, 82, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("VermontDamagedDown", "Resources/Images/Characters/Vermont/VermontDamagedDown.bmp", 50, 68, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("SaladinDamagedLeft", "Resources/Images/Characters/Saladin/SaladinDamagedLeft.bmp", 67, 69, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("SaladinDamagedRight", "Resources/Images/Characters/Saladin/SaladinDamagedRight.bmp", 67, 69, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("SaladinDamagedUp", "Resources/Images/Characters/Saladin/SaladinDamagedUp.bmp", 47, 78, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("SaladinDamagedDown", "Resources/Images/Characters/Saladin/SaladinDamagedDown.bmp", 79, 80, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("SaladinDashLeft", "Resources/Images/Characters/Saladin/SaladinDashLeft.bmp", 83, 74, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("SaladinDashRight", "Resources/Images/Characters/Saladin/SaladinDashRight.bmp", 83, 74, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("SaladinDashUp", "Resources/Images/Characters/Saladin/SaladinDashUp.bmp", 79, 84, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("SaladinDashDown", "Resources/Images/Characters/Saladin/SaladinDashDown.bmp", 67, 80, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("VermontSkillCasting", "Resources/Images/Characters/Vermont/VermontSkillCasting.bmp", 53, 73, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("VermontSkillUp", "Resources/Images/Characters/Vermont/VermontSkillUp.bmp", 26, 131, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("VermontSkillDown", "Resources/Images/Characters/Vermont/VermontSkillDown.bmp", 32, 122, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("VermontSkillLeft", "Resources/Images/Characters/Vermont/VermontSkillLeft.bmp", 117, 63, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("VermontSkillRight", "Resources/Images/Characters/Vermont/VermontSkillRight.bmp", 117, 64, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("BattleEnd", "Resources/Images/UI/BattleEnd.bmp", WINSIZE_X, 90, true, RGB(0, 4, 4));
	IMAGEMANAGER->addImage("Scenario", "Resources/Images/UI/Scenario.bmp", 189, 35, true, RGB(8, 36, 44));
	IMAGEMANAGER->addImage("Clear", "Resources/Images/UI/Clear.bmp", 119, 36, true, RGB(8, 36, 44));
	IMAGEMANAGER->addImage("TextBox2", "Resources/Images/UI/TextBox2.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("TextBoxLT", "Resources/Images/UI/TextBoxLT.bmp", 5, 5);
	IMAGEMANAGER->addImage("TextBoxLB", "Resources/Images/UI/TextBoxLB.bmp", 5, 5);
	IMAGEMANAGER->addImage("TextBoxRT", "Resources/Images/UI/TextBoxRT.bmp", 5, 5);
	IMAGEMANAGER->addImage("TextBoxRB", "Resources/Images/UI/TextBoxRB.bmp", 5, 5);
	IMAGEMANAGER->addImage("TextBoxRB", "Resources/Images/UI/TextBoxRB.bmp", 5, 5);
	IMAGEMANAGER->addImage("TextBoxRB", "Resources/Images/UI/TextBoxRB.bmp", 5, 5);
	IMAGEMANAGER->addImage("TextBoxRB", "Resources/Images/UI/TextBoxRB.bmp", 5, 5);
	IMAGEMANAGER->addImage("TextBoxRB", "Resources/Images/UI/TextBoxRB.bmp", 5, 5);
	IMAGEMANAGER->addImage("Snow", "Resources/Images/Effects/SkillEffect/Snow.bmp", 12, 12, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("ShopEmployee", "Resources/Images/UI/Shop/ShopEmployee.bmp", 300, 460, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("자마드 아그니", "Resources/Images/UI/Shop/자마드 아그니.bmp", 24, 24);
	IMAGEMANAGER->addImage("브리트라", "Resources/Images/UI/Shop/브리트라.bmp", 24, 24);
	IMAGEMANAGER->addImage("돌격소총", "Resources/Images/UI/Shop/돌격소총.bmp", 24, 24);
	IMAGEMANAGER->addImage("스나이퍼 건", "Resources/Images/UI/Shop/스나이퍼 건.bmp", 24, 24);
	IMAGEMANAGER->addImage("테슈브", "Resources/Images/UI/Shop/테슈브.bmp", 24, 24);
	IMAGEMANAGER->addImage("벽력궁", "Resources/Images/UI/Shop/벽력궁.bmp", 24, 24);
	IMAGEMANAGER->addImage("다마스커스", "Resources/Images/UI/Shop/다마스커스.bmp", 24, 24);
	IMAGEMANAGER->addImage("방탄복", "Resources/Images/UI/Shop/방탄복.bmp", 24, 24);
	IMAGEMANAGER->addImage("스피드 슈즈", "Resources/Images/UI/Shop/스피드 슈즈.bmp", 24, 24);
	IMAGEMANAGER->addImage("UpButton", "Resources/Images/UI/Shop/UpButton.bmp", 12, 16);
	IMAGEMANAGER->addImage("DownButton", "Resources/Images/UI/Shop/DownButton.bmp", 12, 16);
	IMAGEMANAGER->addImage("UpButtonPress", "Resources/Images/UI/Shop/UpButtonPress.bmp", 12, 16);
	IMAGEMANAGER->addImage("DownButtonPress", "Resources/Images/UI/Shop/DownButtonPress.bmp", 12, 16);
	IMAGEMANAGER->addImage("ScrollUpButton", "Resources/Images/UI/Shop/ScrollUpButton.bmp", 16, 16);
	IMAGEMANAGER->addImage("ScrollDownButton", "Resources/Images/UI/Shop/ScrollDownButton.bmp", 16, 16);
	IMAGEMANAGER->addImage("ScrollButton", "Resources/Images/UI/Shop/ScrollButton.bmp", 16, 16);
	IMAGEMANAGER->addImage("Pattern1", "Resources/Images/UI/Shop/Pattern1.bmp", 255, 92, true, RGB(252, 252, 252));
	IMAGEMANAGER->addImage("Pattern2", "Resources/Images/UI/Shop/Pattern2.bmp", 255, 92, true, RGB(252, 252, 252));
	IMAGEMANAGER->addImage("ItemNum", "Resources/Images/UI/Shop/ItemNum.bmp", 17, 16);
	IMAGEMANAGER->addFrameImage("LoadingSceneBG", "Resources/Images/BackGrounds/LoadingScene/LoadingSceneBG.bmp", 16400, 200, 41, 1);
	IMAGEMANAGER->addFrameImage("Cham", "Resources/Images/Effects/SkillEffect/풍아열공참/Cham.bmp", 6780, 235, 30, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("SlashLight", "Resources/Images/Effects/SkillEffect/풍아열공참/SlashLight.bmp", 3441, 109, 31, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("Charging", "Resources/Images/Effects/SkillEffect/풍아열공참/Charging.bmp", 12, 12, true, RGB(0, 68, 0));
	IMAGEMANAGER->addFrameImage("SaladinAttackUpEffect", "Resources/Images/Effects/SkillEffect/SaladinAttackUpEffect.bmp", 945, 163, 7, 1, true, RGB(0, 68, 0));
	IMAGEMANAGER->addFrameImage("SaladinAttackSideEffect", "Resources/Images/Effects/SkillEffect/SaladinAttackSideEffect.bmp", 1274, 288, 7, 2, true, RGB(0, 68, 0));
	IMAGEMANAGER->addFrameImage("SaladinAttackDownEffect", "Resources/Images/Effects/SkillEffect/SaladinAttackDownEffect.bmp", 945, 163, 7, 1, true, RGB(0, 68, 0));
	IMAGEMANAGER->addFrameImage("VermontSkillEFX1", "Resources/Images/Effects/SkillEffect/VermontSkillEFX1.bmp", 3069, 126, 31, 1, true, RGB(0, 92, 0));
	IMAGEMANAGER->addFrameImage("VermontSkillEFX2", "Resources/Images/Effects/SkillEffect/VermontSkillEFX2.bmp", 2755, 144, 19, 1, true, RGB(4, 176, 236));
	IMAGEMANAGER->addFrameImage("VermontSkillEFX3", "Resources/Images/Effects/SkillEffect/VermontSkillEFX3.bmp", 1768, 65, 26, 1, true, RGB(192, 196, 244));
	IMAGEMANAGER->addFrameImage("VermontSkillEFX4", "Resources/Images/Effects/SkillEffect/VermontSkillEFX4.bmp", 408, 32, 12, 1, true, RGB(232, 224, 176));
	IMAGEMANAGER->addFrameImage("VermontSkillEFX5", "Resources/Images/Effects/SkillEffect/VermontSkillEFX5.bmp", 480, 40, 12, 1, true, RGB(168, 168, 172));
	IMAGEMANAGER->addFrameImage("SkillCasting", "Resources/Images/Effects/SkillEffect/SkillCasting.bmp", 6325, 192, 25, 1, true, RGB(80, 0, 0));
	IMAGEMANAGER->addFrameImage("Volcano", "Resources/Images/Effects/SkillEffect/Saladin/Volcano.bmp", 696, 45, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("CrackedEarth1RU", "Resources/Images/Effects/SkillEffect/Saladin/CrackedEarth1RU.bmp", 480, 32, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("CrackedEarth2RU", "Resources/Images/Effects/SkillEffect/Saladin/CrackedEarth2RU.bmp", 480, 32, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("CrackedEarth3RU", "Resources/Images/Effects/SkillEffect/Saladin/CrackedEarth3RU.bmp", 480, 32, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("CrackedEarth1LU", "Resources/Images/Effects/SkillEffect/Saladin/CrackedEarth1LU.bmp", 480, 32, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("CrackedEarth2LU", "Resources/Images/Effects/SkillEffect/Saladin/CrackedEarth2LU.bmp", 480, 32, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("CrackedEarth3LU", "Resources/Images/Effects/SkillEffect/Saladin/CrackedEarth3LU.bmp", 480, 32, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("RestoreEarth1RU", "Resources/Images/Effects/SkillEffect/Saladin/RestoreEarth1RU.bmp", 320, 32, 8, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("RestoreEarth2RU", "Resources/Images/Effects/SkillEffect/Saladin/RestoreEarth2RU.bmp", 320, 32, 8, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("RestoreEarth3RU", "Resources/Images/Effects/SkillEffect/Saladin/RestoreEarth3RU.bmp", 320, 32, 8, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("RestoreEarth1LU", "Resources/Images/Effects/SkillEffect/Saladin/RestoreEarth1LU.bmp", 320, 32, 8, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("RestoreEarth2LU", "Resources/Images/Effects/SkillEffect/Saladin/RestoreEarth2LU.bmp", 320, 32, 8, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("RestoreEarth3LU", "Resources/Images/Effects/SkillEffect/Saladin/RestoreEarth3LU.bmp", 320, 32, 8, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("Eruption1RU", "Resources/Images/Effects/SkillEffect/Saladin/Eruption1RU.bmp", 1280, 252, 32, 1, true, RGB(252, 236, 212));
	IMAGEMANAGER->addFrameImage("Eruption2RU", "Resources/Images/Effects/SkillEffect/Saladin/Eruption2RU.bmp", 1280, 252, 32, 1, true, RGB(252, 236, 212));
	IMAGEMANAGER->addFrameImage("Eruption3RU", "Resources/Images/Effects/SkillEffect/Saladin/Eruption3RU.bmp", 1200, 252, 30, 1, true, RGB(252, 236, 212));
	IMAGEMANAGER->addFrameImage("Eruption1LU", "Resources/Images/Effects/SkillEffect/Saladin/Eruption1LU.bmp", 1280, 252, 32, 1, true, RGB(252, 236, 212));
	IMAGEMANAGER->addFrameImage("Eruption2LU", "Resources/Images/Effects/SkillEffect/Saladin/Eruption2LU.bmp", 1280, 252, 32, 1, true, RGB(252, 236, 212));
	IMAGEMANAGER->addFrameImage("Eruption3LU", "Resources/Images/Effects/SkillEffect/Saladin/Eruption3LU.bmp", 1200, 252, 30, 1, true, RGB(252, 236, 212));
	IMAGEMANAGER->addFrameImage("Magma1LU", "Resources/Images/Effects/SkillEffect/Saladin/Magma1LU.bmp", 480, 230, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("Magma2LU", "Resources/Images/Effects/SkillEffect/Saladin/Magma2LU.bmp", 480, 226, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("Magma3LU", "Resources/Images/Effects/SkillEffect/Saladin/Magma3LU.bmp", 492, 93, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("Magma1RU", "Resources/Images/Effects/SkillEffect/Saladin/Magma1RU.bmp", 480, 230, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("Magma2RU", "Resources/Images/Effects/SkillEffect/Saladin/Magma2RU.bmp", 480, 226, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("Magma3RU", "Resources/Images/Effects/SkillEffect/Saladin/Magma3RU.bmp", 492, 93, 12, 1, true, RGB(8, 88, 8));
	IMAGEMANAGER->addFrameImage("Explosion", "Resources/Images/Effects/SkillEffect/Saladin/Explosion.bmp", 3432, 130, 24, 1, true, RGB(4, 72, 4));
	IMAGEMANAGER->addFrameImage("Explosion2", "Resources/Images/Effects/SkillEffect/Saladin/Explosion2.bmp", 872, 131, 8, 1, true, RGB(4, 108, 0));
	IMAGEMANAGER->addFrameImage("Explosion3", "Resources/Images/Effects/SkillEffect/Saladin/Explosion3.bmp", 6804, 252, 28, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("Stone1", "Resources/Images/Effects/SkillEffect/Saladin/Stone1.bmp", 210, 14, 15, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Stone2", "Resources/Images/Effects/SkillEffect/Saladin/Stone2.bmp", 465, 30, 15, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("ShockWave", "Resources/Images/Effects/SkillEffect/Saladin/ShockWave.bmp", 6368, 157, 32, 1, true, RGB(4, 108, 0));
	IMAGEMANAGER->addFrameImage("VermontAttackUp", "Resources/Images/Characters/Vermont/VermontAttackUp.bmp", 464, 85, 4, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("VermontAttackDown", "Resources/Images/Characters/Vermont/VermontAttackDown.bmp", 420, 104, 4, 1, true, RGB(255, 0, 255));
	IMAGEMANAGER->addFrameImage("SaladinSkill", "Resources/Images/Characters/Saladin/SaladinSkill.bmp", 1100, 101, 11, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("FireFly", "Resources/Images/Effects/StoryScene/FireFly.bmp", 6882, 249, 31, 1, true, RGB(4, 0, 4));

	// 적 병사 이미지
	IMAGEMANAGER->addFrameImage("Soldier1IdleUp", "Resources/Images/Characters/Soldier1/Soldier1IdleUp.bmp", 90, 75, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier1IdleDown", "Resources/Images/Characters/Soldier1/Soldier1IdleDown.bmp", 108, 75, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier1IdleSide", "Resources/Images/Characters/Soldier1/Soldier1IdleSide.bmp", 141, 156, 3, 2, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier1MoveUp", "Resources/Images/Characters/Soldier1/Soldier1MoveUp.bmp", 246, 75, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier1MoveSide", "Resources/Images/Characters/Soldier1/Soldier1MoveSide.bmp", 264, 152, 6, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier1MoveDown", "Resources/Images/Characters/Soldier1/Soldier1MoveDown.bmp", 228, 75, 6, 1, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier1AttackUp", "Resources/Images/Characters/Soldier1/Soldier1AttackUp.bmp", 116, 106, 4, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier1AttackSide", "Resources/Images/Characters/Soldier1/Soldier1AttackSide.bmp", 356, 216, 4, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier1AttackDown", "Resources/Images/Characters/Soldier1/Soldier1AttackDown.bmp", 140, 80, 4, 1, true, RGB(0, 0, 0));

	IMAGEMANAGER->addImage("Soldier1DamagedUp", "Resources/Images/Characters/Soldier1/Soldier1DamagedUp.bmp", 39, 62, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier1DamagedSide", "Resources/Images/Characters/Soldier1/Soldier1DamagedSide.bmp", 45, 110, 1, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier1DamagedDown", "Resources/Images/Characters/Soldier1/Soldier1DamagedDown.bmp", 57, 61, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier2IdleUp", "Resources/Images/Characters/Soldier2/Soldier2IdleUp.bmp", 129, 87, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier2IdleDown", "Resources/Images/Characters/Soldier2/Soldier2IdleDown.bmp", 135, 96, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier2IdleSide", "Resources/Images/Characters/Soldier2/Soldier2IdleSide.bmp", 96, 196, 3, 2, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier2MoveUp", "Resources/Images/Characters/Soldier2/Soldier2MoveUp.bmp", 264, 100, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier2MoveSide", "Resources/Images/Characters/Soldier2/Soldier2MoveSide.bmp", 522, 194, 6, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier2MoveDown", "Resources/Images/Characters/Soldier2/Soldier2MoveDown.bmp", 264, 89, 6, 1, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier2AttackUp", "Resources/Images/Characters/Soldier2/Soldier2AttackUp.bmp", 968, 141, 8, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier2AttackSide", "Resources/Images/Characters/Soldier2/Soldier2AttackSide.bmp", 1376, 216, 8, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier2AttackDown", "Resources/Images/Characters/Soldier2/Soldier2AttackDown.bmp", 984, 154, 8, 1, true, RGB(0, 0, 0));

	IMAGEMANAGER->addImage("Soldier2DamagedUp", "Resources/Images/Characters/Soldier2/Soldier2DamagedUp.bmp", 40, 87, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier2DamagedSide", "Resources/Images/Characters/Soldier2/Soldier2DamagedSide.bmp", 44, 188, 1, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier2DamagedDown", "Resources/Images/Characters/Soldier2/Soldier2DamagedDown.bmp", 49, 99, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier3IdleUp", "Resources/Images/Characters/Soldier3/Soldier3IdleUp.bmp", 114, 68, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier3IdleDown", "Resources/Images/Characters/Soldier3/Soldier3IdleDown.bmp", 126, 67, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier3IdleSide", "Resources/Images/Characters/Soldier3/Soldier3IdleSide.bmp", 117, 134, 3, 2, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier3MoveUp", "Resources/Images/Characters/Soldier3/Soldier3MoveUp.bmp", 276, 70, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier3MoveSide", "Resources/Images/Characters/Soldier3/Soldier3MoveSide.bmp", 408, 138, 6, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier3MoveDown", "Resources/Images/Characters/Soldier3/Soldier3MoveDown.bmp", 264, 67, 6, 1, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier3AttackUp", "Resources/Images/Characters/Soldier3/Soldier3AttackUp.bmp", 264, 80, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier3AttackSide", "Resources/Images/Characters/Soldier3/Soldier3AttackSide.bmp", 348, 134, 6, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier3AttackDown", "Resources/Images/Characters/Soldier3/Soldier3AttackDown.bmp", 312, 72, 6, 1, true, RGB(0, 0, 0));

	IMAGEMANAGER->addImage("Soldier3DamagedUp", "Resources/Images/Characters/Soldier3/Soldier3DamagedUp.bmp", 39, 65, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier3DamagedSide", "Resources/Images/Characters/Soldier3/Soldier3DamagedSide.bmp", 48, 104, 1, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier3DamagedDown", "Resources/Images/Characters/Soldier3/Soldier3DamagedDown.bmp", 40, 50, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier4IdleUp", "Resources/Images/Characters/Soldier4/Soldier4IdleUp.bmp", 150, 71, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier4IdleDown", "Resources/Images/Characters/Soldier4/Soldier4IdleDown.bmp", 123, 72, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier4IdleSide", "Resources/Images/Characters/Soldier4/Soldier4IdleSide.bmp", 168, 138, 3, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier4MoveUp", "Resources/Images/Characters/Soldier4/Soldier4MoveUp.bmp", 204, 99, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier4MoveSide", "Resources/Images/Characters/Soldier4/Soldier4MoveSide.bmp", 426, 172, 6, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier4MoveDown", "Resources/Images/Characters/Soldier4/Soldier4MoveDown.bmp", 324, 85, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier4AttackUp", "Resources/Images/Characters/Soldier4/Soldier4AttackUp.bmp", 945, 127, 9, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier4AttackSide", "Resources/Images/Characters/Soldier4/Soldier4AttackSide.bmp", 1224, 204, 9, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier4AttackDown", "Resources/Images/Characters/Soldier4/Soldier4AttackDown.bmp", 909, 129, 9, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier4DamagedUp", "Resources/Images/Characters/Soldier4/Soldier4DamagedUp.bmp", 41, 70, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier4DamagedSide", "Resources/Images/Characters/Soldier4/Soldier4DamagedSide.bmp", 62, 116, 1, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier4DamagedDown", "Resources/Images/Characters/Soldier4/Soldier4DamagedDown.bmp", 59, 57, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier5IdleUp", "Resources/Images/Characters/Soldier5/Soldier5IdleUp.bmp", 90, 73, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier5IdleDown", "Resources/Images/Characters/Soldier5/Soldier5IdleDown.bmp", 90, 74, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier5IdleSide", "Resources/Images/Characters/Soldier5/Soldier5IdleSide.bmp", 150, 150, 3, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier5MoveUp", "Resources/Images/Characters/Soldier5/Soldier5MoveUp.bmp", 198, 72, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier5MoveSide", "Resources/Images/Characters/Soldier5/Soldier5MoveSide.bmp", 275, 136, 5, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier5MoveDown", "Resources/Images/Characters/Soldier5/Soldier5MoveDown.bmp", 210, 73, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier5AttackUp", "Resources/Images/Characters/Soldier5/Soldier5AttackUp.bmp", 132, 72, 4, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier5AttackSide", "Resources/Images/Characters/Soldier5/Soldier5AttackSide.bmp", 220, 150, 4, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier5AttackDown", "Resources/Images/Characters/Soldier5/Soldier5AttackDown.bmp", 136, 73, 4, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier5DamagedUp", "Resources/Images/Characters/Soldier5/Soldier5DamagedUp.bmp", 36, 64, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier5DamagedSide", "Resources/Images/Characters/Soldier5/Soldier5DamagedSide.bmp", 50, 118, 1, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier5DamagedDown", "Resources/Images/Characters/Soldier5/Soldier5DamagedDown.bmp", 35, 60, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier6IdleUp", "Resources/Images/Characters/Soldier6/Soldier6IdleUp.bmp", 111, 68, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier6IdleDown", "Resources/Images/Characters/Soldier6/Soldier6IdleDown.bmp", 111, 69, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier6IdleSide", "Resources/Images/Characters/Soldier6/Soldier6IdleSide.bmp", 99, 146, 3, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier6MoveUp", "Resources/Images/Characters/Soldier6/Soldier6MoveUp.bmp", 228, 67, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier6MoveSide", "Resources/Images/Characters/Soldier6/Soldier6MoveSide.bmp", 294, 138, 6, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier6MoveDown", "Resources/Images/Characters/Soldier6/Soldier6MoveDown.bmp", 204, 69, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier6AttackUp", "Resources/Images/Characters/Soldier6/Soldier6AttackUp.bmp", 720, 70, 8, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier6AttackSide", "Resources/Images/Characters/Soldier6/Soldier6AttackSide.bmp", 800, 174, 8, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier6AttackDown", "Resources/Images/Characters/Soldier6/Soldier6AttackDown.bmp", 864, 91, 8, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier6DamagedUp", "Resources/Images/Characters/Soldier6/Soldier6DamagedUp.bmp", 40, 56, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier6DamagedSide", "Resources/Images/Characters/Soldier6/Soldier6DamagedSide.bmp", 42, 114, 1, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier6DamagedDown", "Resources/Images/Characters/Soldier6/Soldier6DamagedDown.bmp", 47, 41, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier8IdleUp", "Resources/Images/Characters/Soldier8/Soldier8IdleUp.bmp", 135, 74, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier8IdleDown", "Resources/Images/Characters/Soldier8/Soldier8IdleDown.bmp", 111, 72, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier8IdleSide", "Resources/Images/Characters/Soldier8/Soldier8IdleSide.bmp", 126, 144, 3, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier8MoveUp", "Resources/Images/Characters/Soldier8/Soldier8MoveUp.bmp", 252, 97, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier8MoveSide", "Resources/Images/Characters/Soldier8/Soldier8MoveSide.bmp", 468, 152, 6, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier8MoveDown", "Resources/Images/Characters/Soldier8/Soldier8MoveDown.bmp", 240, 71, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier8AttackUp", "Resources/Images/Characters/Soldier8/Soldier8AttackUp.bmp", 928, 109, 8, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier8AttackSide", "Resources/Images/Characters/Soldier8/Soldier8AttackSide.bmp", 720, 180, 8, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier8AttackDown", "Resources/Images/Characters/Soldier8/Soldier8AttackDown.bmp", 928, 102, 8, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier8DamagedUp", "Resources/Images/Characters/Soldier8/Soldier8DamagedUp.bmp", 63, 56, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier8DamagedSide", "Resources/Images/Characters/Soldier8/Soldier8DamagedSide.bmp", 61, 102, 1, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier8DamagedDown", "Resources/Images/Characters/Soldier8/Soldier8DamagedDown.bmp", 48, 51, true, RGB(0, 0, 0));

	IMAGEMANAGER->addFrameImage("Soldier9IdleUp", "Resources/Images/Characters/Soldier9/Soldier9IdleUp.bmp", 99, 75, 3, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Soldier9IdleDown", "Resources/Images/Characters/Soldier9/Soldier9IdleDown.bmp", 93, 76, 3, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Soldier9IdleSide", "Resources/Images/Characters/Soldier9/Soldier9IdleSide.bmp", 141, 146, 3, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Soldier9MoveUp", "Resources/Images/Characters/Soldier9/Soldier9MoveUp.bmp", 204, 76, 6, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Soldier9MoveSide", "Resources/Images/Characters/Soldier9/Soldier9MoveSide.bmp", 354, 134, 6, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Soldier9MoveDown", "Resources/Images/Characters/Soldier9/Soldier9MoveDown.bmp", 192, 70, 6, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Soldier9AttackUp", "Resources/Images/Characters/Soldier9/Soldier9AttackUp.bmp", 304, 71, 4, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Soldier9AttackSide", "Resources/Images/Characters/Soldier9/Soldier9AttackSide.bmp", 316, 126, 4, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Soldier9AttackDown", "Resources/Images/Characters/Soldier9/Soldier9AttackDown.bmp", 292, 79, 4, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("Soldier9DamagedUp", "Resources/Images/Characters/Soldier9/Soldier9DamagedUp.bmp", 39, 79, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Soldier9DamagedSide", "Resources/Images/Characters/Soldier9/Soldier9DamagedSide.bmp", 66, 122, 1, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("Soldier9DamagedDown", "Resources/Images/Characters/Soldier9/Soldier9DamagedDown.bmp", 42, 61, true, RGB(168, 208, 168));

	IMAGEMANAGER->addFrameImage("Soldier10IdleUp", "Resources/Images/Characters/Soldier10/Soldier10IdleUp.bmp", 93, 78, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier10IdleDown", "Resources/Images/Characters/Soldier10/Soldier10IdleDown.bmp", 138, 64, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier10IdleSide", "Resources/Images/Characters/Soldier10/Soldier10IdleSide.bmp", 174, 136, 3, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier10MoveUp", "Resources/Images/Characters/Soldier10/Soldier10MoveUp.bmp", 300, 71, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier10MoveSide", "Resources/Images/Characters/Soldier10/Soldier10MoveSide.bmp", 378, 136, 6, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier10MoveDown", "Resources/Images/Characters/Soldier10/Soldier10MoveDown.bmp", 294, 72, 6, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier10AttackUp", "Resources/Images/Characters/Soldier10/Soldier10AttackUp.bmp", 140, 93, 5, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier10AttackSide", "Resources/Images/Characters/Soldier10/Soldier10AttackSide.bmp", 320, 140, 5, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier10AttackDown", "Resources/Images/Characters/Soldier10/Soldier10AttackDown.bmp", 180, 71, 5, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier10DamagedUp", "Resources/Images/Characters/Soldier10/Soldier10DamagedUp.bmp", 29, 64, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Soldier10DamagedSide", "Resources/Images/Characters/Soldier10/Soldier10DamagedSide.bmp", 53, 104, 1, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Soldier10DamagedDown", "Resources/Images/Characters/Soldier10/Soldier10DamagedDown.bmp", 39, 48, true, RGB(0, 0, 0));

	// 철가면 이미지
	IMAGEMANAGER->addFrameImage("IronMaskIdleUp", "Resources/Images/Characters/IronMask/IronMaskIdleUp.bmp", 186, 93, 3, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("IronMaskIdleDown", "Resources/Images/Characters/IronMask/IronMaskIdleDown.bmp", 186, 93, 3, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("IronMaskIdleSide", "Resources/Images/Characters/IronMask/IronMaskIdleSide.bmp", 177, 176, 3, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("IronMaskMoveUp", "Resources/Images/Characters/IronMask/IronMaskMoveUp.bmp", 660, 85, 6, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("IronMaskMoveDown", "Resources/Images/Characters/IronMask/IronMaskMoveDown.bmp", 672, 87, 6, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("IronMaskMoveSide", "Resources/Images/Characters/IronMask/IronMaskMoveSide.bmp", 546, 160, 6, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("IronMaskAttackUp", "Resources/Images/Characters/IronMask/IronMaskAttackUp.bmp", 928, 161, 8, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("IronMaskAttackDown", "Resources/Images/Characters/IronMask/IronMaskAttackDown.bmp", 944, 183, 8, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("IronMaskAttackSide", "Resources/Images/Characters/IronMask/IronMaskAttackSide.bmp", 1480, 236, 8, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("IronMaskDamagedUp", "Resources/Images/Characters/IronMask/IronMaskDamagedUp.bmp", 55, 71, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("IronMaskDamagedDown", "Resources/Images/Characters/IronMask/IronMaskDamagedDown.bmp", 83, 73, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("IronMaskDamagedSide", "Resources/Images/Characters/IronMask/IronMaskDamagedSide.bmp", 84, 146, 1, 2, true, RGB(168, 208, 168));

	// 크리스티앙 이미지
	IMAGEMANAGER->addImage("크리스티앙Mini", "Resources/Images/UI/ChristianMini.bmp", 50, 50);
	IMAGEMANAGER->addFrameImage("ChristianIdleUp", "Resources/Images/Characters/Christian/ChristianIdleUp.bmp", 87, 74, 3, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("ChristianIdleDown", "Resources/Images/Characters/Christian/ChristianIdleDown.bmp", 99, 75, 3, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("ChristianIdleSide", "Resources/Images/Characters/Christian/ChristianIdleSide.bmp", 99, 148, 3, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("ChristianMoveUp", "Resources/Images/Characters/Christian/ChristianMoveUp.bmp", 222, 72, 6, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("ChristianMoveDown", "Resources/Images/Characters/Christian/ChristianMoveDown.bmp", 216, 73, 6, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("ChristianMoveSide", "Resources/Images/Characters/Christian/ChristianMoveSide.bmp", 264, 140, 6, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("ChristianAttackUp", "Resources/Images/Characters/Christian/ChristianAttackUp.bmp", 852, 97, 12, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("GunFireUp", "Resources/Images/Characters/Christian/GunFireUp.bmp", 616, 85, 8, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("ChristianAttackDown", "Resources/Images/Characters/Christian/ChristianAttackDown.bmp", 726, 83, 11, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("GunFireDown", "Resources/Images/Characters/Christian/GunFireDown.bmp", 616, 85, 8, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("ChristianAttackSide", "Resources/Images/Characters/Christian/ChristianAttackSide.bmp", 700, 194, 10, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("GunFireSide", "Resources/Images/Characters/Christian/GunFireSide.bmp", 680, 154, 8, 2, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("ChristianDamagedUp", "Resources/Images/Characters/Christian/ChristianDamagedUp.bmp", 27, 68, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("ChristianDamagedDown", "Resources/Images/Characters/Christian/ChristianDamagedDown.bmp", 36, 61, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("ChristianDamagedSide", "Resources/Images/Characters/Christian/ChristianDamagedSide.bmp", 44, 114, 1, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("GunTurnSide", "Resources/Images/Characters/Christian/GunTurnSide.bmp", 200, 50, 8, 2, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("GunTurnUpDown", "Resources/Images/Characters/Christian/GunTurnUpDown.bmp", 40, 24, 8, 2, true, RGB(168, 208, 168));

	// 죠안 이미지
	IMAGEMANAGER->addImage("죠안 카트라이트Mini", "Resources/Images/UI/JoanMini.bmp", 50, 50);

	// 아지다하카
	IMAGEMANAGER->addFrameImage("AjdahakaUp", "Resources/Images/Characters/Ajdahaka/AjdahakaUp.bmp", 2880, 141, 12, 1, true, RGB(8, 8, 4));
	IMAGEMANAGER->addFrameImage("AjdahakaDown", "Resources/Images/Characters/Ajdahaka/AjdahakaDown.bmp", 2868, 161, 12, 1, true, RGB(8, 8, 4));
	IMAGEMANAGER->addFrameImage("AjdahakaSide", "Resources/Images/Characters/Ajdahaka/AjdahakaSide.bmp", 1800, 458, 12, 2, true, RGB(8, 8, 4));

	//UI
	IMAGEMANAGER->addFrameImage("FingerCursor", "Resources/Images/UI/FingerCursor.bmp", 105, 27, 5, 1, true, RGB(80, 120, 116));
	IMAGEMANAGER->addFrameImage("PreferenceIcon", "Resources/Images/UI/PreferenceIcon.bmp", 98, 15, 7, 1, true, RGB(220, 160, 168));
	IMAGEMANAGER->addImage("LaunchTile", "Resources/Images/UI/LaunchTile.bmp", 40, 30);
	IMAGEMANAGER->addImage("Episode", "Resources/Images/UI/Episode.bmp", 26, 6, true, RGB(220, 160, 168));
	IMAGEMANAGER->addImage("Chapter", "Resources/Images/UI/Chapter.bmp", 28, 6, true, RGB(220, 160, 168));
	IMAGEMANAGER->addImage("Time", "Resources/Images/UI/Time.bmp", 14, 6, true, RGB(220, 160, 168));
	IMAGEMANAGER->addFrameImage("NextDialog", "Resources/Images/UI/NextDialog.bmp", 54, 8, 6, 1, true, RGB(0, 252, 0));
	IMAGEMANAGER->addFrameImage("SaveLoadIcon", "Resources/Images/UI/SaveLoadIcon.bmp", 39, 15, 3, 1, true, RGB(220, 160, 168));
	IMAGEMANAGER->addImage("BulletPoint", "Resources/Images/UI/BulletPoint.bmp", 2, 2);

	// 스토리씬 배경
	IMAGEMANAGER->addImage("StoryBG69-1", "Resources/Images/BackGrounds/StoryScene/StoryBG69-1.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("StoryBG69-2", "Resources/Images/BackGrounds/StoryScene/StoryBG69-2.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("StoryBG69-3", "Resources/Images/BackGrounds/StoryScene/StoryBG69-3.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("StoryBG69-4", "Resources/Images/BackGrounds/StoryScene/StoryBG69-4.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("StoryBG69-5", "Resources/Images/BackGrounds/StoryScene/StoryBG69-5.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("StoryBG69-6", "Resources/Images/BackGrounds/StoryScene/StoryBG69-6.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("StoryBG69-7", "Resources/Images/BackGrounds/StoryScene/StoryBG69-7.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("StoryBG69-8", "Resources/Images/BackGrounds/StoryScene/StoryBG69-8.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("StoryBG69-9", "Resources/Images/BackGrounds/StoryScene/StoryBG69-9.bmp", WINSIZE_X, WINSIZE_Y);
	IMAGEMANAGER->addImage("StoryObject69-1", "Resources/Images/BackGrounds/StoryScene/StoryObject69-1.bmp", 56, 76, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("StoryObject69-2", "Resources/Images/BackGrounds/StoryScene/StoryObject69-2.bmp", 43, 76, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("StoryObject69-3", "Resources/Images/BackGrounds/StoryScene/StoryObject69-3.bmp", 38, 69, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("StoryObject69-4", "Resources/Images/BackGrounds/StoryScene/StoryObject69-4.bmp", 31, 73, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("StoryObject69-5", "Resources/Images/BackGrounds/StoryScene/StoryObject69-5.bmp", 27, 75, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("StoryObject69-6", "Resources/Images/BackGrounds/StoryScene/StoryObject69-6.bmp", 25, 67, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("StoryObject69-7", "Resources/Images/BackGrounds/StoryScene/StoryObject69-7.bmp", 31, 77, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("StoryObject69-8", "Resources/Images/BackGrounds/StoryScene/StoryObject69-8.bmp", 37, 75, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("StoryObject69-9", "Resources/Images/BackGrounds/StoryScene/StoryObject69-9.bmp", 33, 72, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("StoryObject69-10", "Resources/Images/BackGrounds/StoryScene/StoryObject69-10.bmp", 24, 90, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("StoryObject69-11", "Resources/Images/BackGrounds/StoryScene/StoryObject69-11.bmp", 53, 60, true, RGB(168, 208, 168));
	IMAGEMANAGER->addImage("StoryObject69-12", "Resources/Images/BackGrounds/StoryScene/StoryObject69-12.bmp", 44, 67, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Story69-Saladin", "Resources/Images/BackGrounds/StoryScene/Story69-Saladin.bmp", 186, 65, 3, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Story69-Soldier", "Resources/Images/BackGrounds/StoryScene/Story69-Soldier.bmp", 159, 86, 3, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Story69-Soldier2", "Resources/Images/BackGrounds/StoryScene/Story69-Soldier2.bmp", 858, 79, 13, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Story69-FireUp", "Resources/Images/BackGrounds/StoryScene/Story69-FireUp.bmp", 403, 93, 13, 1, true, RGB(0, 0, 0));
	IMAGEMANAGER->addFrameImage("Story69-Die1", "Resources/Images/BackGrounds/StoryScene/Story69-Die1.bmp", 238, 74, 7, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Story69-Die2", "Resources/Images/BackGrounds/StoryScene/Story69-Die2.bmp", 252, 76, 7, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Story69-Die3", "Resources/Images/BackGrounds/StoryScene/Story69-Die3.bmp", 266, 79, 7, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Story69-Osman", "Resources/Images/BackGrounds/StoryScene/Story69-Osman.bmp", 832, 81, 13, 1, true, RGB(168, 208, 168));
	IMAGEMANAGER->addFrameImage("Story69-Yan", "Resources/Images/BackGrounds/StoryScene/Story69-Yan.bmp", 1120, 71, 16, 1, true, RGB(168, 208, 168));

	// 대화 캐릭터 이미지
	IMAGEMANAGER->addImage("Dialog발라", "Resources/Images/BackGrounds/StoryScene/Dialog발라.bmp", 395, 415, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("Dialog오스만", "Resources/Images/BackGrounds/StoryScene/Dialog오스만.bmp", 426, 418, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("Dialog얀", "Resources/Images/BackGrounds/StoryScene/Dialog얀.bmp", 296, 446, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("Dialog알 아샤", "Resources/Images/BackGrounds/StoryScene/Dialog알 아샤.bmp", 285, 421, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("Dialog아두스 베이", "Resources/Images/BackGrounds/StoryScene/Dialog아두스 베이.bmp", 255, 440, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("Dialog라쉬카", "Resources/Images/BackGrounds/StoryScene/Dialog라쉬카.bmp", 396, 429, true, RGB(255, 0, 255));
	IMAGEMANAGER->addImage("Dialog무카파", "Resources/Images/BackGrounds/StoryScene/Dialog무카파.bmp", 339, 434, true, RGB(0, 0, 0));
	IMAGEMANAGER->addImage("Dialog멘붕살라딘", "Resources/Images/BackGrounds/StoryScene/Dialog멘붕살라딘.bmp", 278, 444, true, RGB(255, 0, 255));

	// SOUND
	SOUNDMANAGER->addSoundFMOD("Brother", "Resources/Sounds/EndingScene/Brother.mp3");
	SOUNDMANAGER->addSoundFMOD("TitleScene", "Resources/Sounds/TitleScene/TitleScene.mp3", true);
	SOUNDMANAGER->addSoundFMOD("ScenarioScene", "Resources/Sounds/ScenarioScene/ScenarioScene.mp3", true);
	SOUNDMANAGER->addSoundFMOD("Select", "Resources/Sounds/SoundEffect/Select.mp3");
	SOUNDMANAGER->addSoundFMOD("Button", "Resources/Sounds/SoundEffect/Button.mp3");
	SOUNDMANAGER->addSoundFMOD("TitleButton", "Resources/Sounds/SoundEffect/TitleButton.wav");
	SOUNDMANAGER->addSoundFMOD("BreakIce", "Resources/Sounds/SoundEffect/BreakIce.wav");
	SOUNDMANAGER->addSoundFMOD("VermontSkillAttack", "Resources/Sounds/SoundEffect/VermontSkillAttack.wav");
	SOUNDMANAGER->addSoundFMOD("SkillCasting", "Resources/Sounds/SoundEffect/SkillCasting.wav");
	SOUNDMANAGER->addSoundFMOD("Blizzard","Resources/Sounds/SoundEffect/Blizzard.wav");
	SOUNDMANAGER->addSoundFMOD("Magma","Resources/Sounds/SoundEffect/Magma.wav");
	SOUNDMANAGER->addSoundFMOD("CrackedEarth","Resources/Sounds/SoundEffect/CrackedEarth.wav");
	SOUNDMANAGER->addSoundFMOD("Explosion","Resources/Sounds/SoundEffect/Explosion.wav");
	SOUNDMANAGER->addSoundFMOD("SaladinSkillStart","Resources/Sounds/SoundEffect/SaladinSkillStart.wav");
	SOUNDMANAGER->addSoundFMOD("FourAttack","Resources/Sounds/SoundEffect/FourAttack.wav");
	SOUNDMANAGER->addSoundFMOD("FinalAttack","Resources/Sounds/SoundEffect/FinalAttack.wav");
	SOUNDMANAGER->addSoundFMOD("혈랑마혼","Resources/Sounds/SoundEffect/Wolf.wav");
	SOUNDMANAGER->addSoundFMOD("Charging","Resources/Sounds/SoundEffect/Charging.wav");
	SOUNDMANAGER->addSoundFMOD("IronMaskAttack1", "Resources/Sounds/SoundEffect/IronMaskAttack1.wav");
	SOUNDMANAGER->addSoundFMOD("Machinegun", "Resources/Sounds/SoundEffect/Machinegun.wav");
	SOUNDMANAGER->addSoundFMOD("Sword", "Resources/Sounds/SoundEffect/Sword.wav");
	SOUNDMANAGER->addSoundFMOD("Tang", "Resources/Sounds/SoundEffect/Tang.wav");

	// 크리스티앙
	SOUNDMANAGER->addSoundFMOD("ChristianFire", "Resources/Sounds/SoundEffect/ChristianFire.wav");
	SOUNDMANAGER->addSoundFMOD("GunLoad", "Resources/Sounds/SoundEffect/GunLoad.wav");

	// 불사조 Story
	SOUNDMANAGER->addSoundFMOD("69-1", "Resources/Sounds/StoryScene/69/69-1.wav");
	SOUNDMANAGER->addSoundFMOD("69-2", "Resources/Sounds/StoryScene/69/69-2.wav");
	SOUNDMANAGER->addSoundFMOD("69-3", "Resources/Sounds/StoryScene/69/69-3.wav");
	SOUNDMANAGER->addSoundFMOD("69-4", "Resources/Sounds/StoryScene/69/69-4.wav");
	SOUNDMANAGER->addSoundFMOD("69-5", "Resources/Sounds/StoryScene/69/69-5.wav");
	SOUNDMANAGER->addSoundFMOD("69-6", "Resources/Sounds/StoryScene/69/69-6.wav");
	SOUNDMANAGER->addSoundFMOD("69-7", "Resources/Sounds/StoryScene/69/69-7.wav");
	SOUNDMANAGER->addSoundFMOD("69-8", "Resources/Sounds/StoryScene/69/69-8.wav");
	SOUNDMANAGER->addSoundFMOD("69-9", "Resources/Sounds/StoryScene/69/69-9.wav");
	SOUNDMANAGER->addSoundFMOD("69-10", "Resources/Sounds/StoryScene/69/69-10.wav");
	SOUNDMANAGER->addSoundFMOD("69-11", "Resources/Sounds/StoryScene/69/69-11.wav");
	SOUNDMANAGER->addSoundFMOD("69-12", "Resources/Sounds/StoryScene/69/69-12.wav");
	SOUNDMANAGER->addSoundFMOD("69-13", "Resources/Sounds/StoryScene/69/69-13.wav");
	SOUNDMANAGER->addSoundFMOD("69-14", "Resources/Sounds/StoryScene/69/69-14.wav");
	SOUNDMANAGER->addSoundFMOD("69-15", "Resources/Sounds/StoryScene/69/69-15.wav");
	SOUNDMANAGER->addSoundFMOD("69-16", "Resources/Sounds/StoryScene/69/69-16.wav");
	SOUNDMANAGER->addSoundFMOD("69-17", "Resources/Sounds/StoryScene/69/69-17.wav");
	SOUNDMANAGER->addSoundFMOD("69-18", "Resources/Sounds/StoryScene/69/69-18.wav");
	SOUNDMANAGER->addSoundFMOD("69-19", "Resources/Sounds/StoryScene/69/69-19.wav");
	SOUNDMANAGER->addSoundFMOD("69-20", "Resources/Sounds/StoryScene/69/69-20.wav");
	SOUNDMANAGER->addSoundFMOD("69-21", "Resources/Sounds/StoryScene/69/69-21.wav");
	SOUNDMANAGER->addSoundFMOD("69-22", "Resources/Sounds/StoryScene/69/69-22.wav");
	SOUNDMANAGER->addSoundFMOD("69-23", "Resources/Sounds/StoryScene/69/69-23.wav");
	SOUNDMANAGER->addSoundFMOD("69-24", "Resources/Sounds/StoryScene/69/69-24.wav");
	SOUNDMANAGER->addSoundFMOD("69-25", "Resources/Sounds/StoryScene/69/69-25.wav");
	SOUNDMANAGER->addSoundFMOD("69-26", "Resources/Sounds/StoryScene/69/69-26.wav");
	SOUNDMANAGER->addSoundFMOD("69-27", "Resources/Sounds/StoryScene/69/69-27.wav");
	SOUNDMANAGER->addSoundFMOD("69-28", "Resources/Sounds/StoryScene/69/69-28.wav");
	SOUNDMANAGER->addSoundFMOD("69-29", "Resources/Sounds/StoryScene/69/69-29.wav");
	SOUNDMANAGER->addSoundFMOD("69-30", "Resources/Sounds/StoryScene/69/69-30.wav");
	SOUNDMANAGER->addSoundFMOD("69-31", "Resources/Sounds/StoryScene/69/69-31.wav");
	SOUNDMANAGER->addSoundFMOD("69-32", "Resources/Sounds/StoryScene/69/69-32.wav");
	SOUNDMANAGER->addSoundFMOD("69-33", "Resources/Sounds/StoryScene/69/69-33.wav");
	SOUNDMANAGER->addSoundFMOD("69-34", "Resources/Sounds/StoryScene/69/69-34.wav");
	SOUNDMANAGER->addSoundFMOD("69-35", "Resources/Sounds/StoryScene/69/69-35.wav");
	SOUNDMANAGER->addSoundFMOD("69-36", "Resources/Sounds/StoryScene/69/69-36.wav");
	SOUNDMANAGER->addSoundFMOD("69-37", "Resources/Sounds/StoryScene/69/69-37.wav");
	SOUNDMANAGER->addSoundFMOD("69-38", "Resources/Sounds/StoryScene/69/69-38.wav");
	SOUNDMANAGER->addSoundFMOD("69-39", "Resources/Sounds/StoryScene/69/69-39.wav");
	SOUNDMANAGER->addSoundFMOD("69-40", "Resources/Sounds/StoryScene/69/69-40.wav");
	SOUNDMANAGER->addSoundFMOD("69-41", "Resources/Sounds/StoryScene/69/69-41.wav");
	SOUNDMANAGER->addSoundFMOD("69-42", "Resources/Sounds/StoryScene/69/69-42.wav");
	SOUNDMANAGER->addSoundFMOD("69-43", "Resources/Sounds/StoryScene/69/69-43.wav");
	SOUNDMANAGER->addSoundFMOD("69-44", "Resources/Sounds/StoryScene/69/69-44.wav");
	SOUNDMANAGER->addSoundFMOD("69-45", "Resources/Sounds/StoryScene/69/69-45.wav");
	SOUNDMANAGER->addSoundFMOD("Flirting", "Resources/Sounds/StoryScene/69/Flirting.wav");
	SOUNDMANAGER->addSoundFMOD("BangBangBang", "Resources/Sounds/StoryScene/69/BangBangBang.wav");
	SOUNDMANAGER->addSoundFMOD("Story69-BG", "Resources/Sounds/StoryScene/69/Story69-BG.wav", true);

	IMAGEMANAGER->addFrameImage("StoryBG", "Resources/Images/BackGrounds/StoryScene/StoryBG.bmp", 3840, 480, 6, 1);
	SOUNDMANAGER->addSoundFMOD("Dialog0", "Resources/Sounds/StoryScene/0.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog1", "Resources/Sounds/StoryScene/1.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog2", "Resources/Sounds/StoryScene/2.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog3", "Resources/Sounds/StoryScene/3.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog4", "Resources/Sounds/StoryScene/4.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog5", "Resources/Sounds/StoryScene/5.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog6", "Resources/Sounds/StoryScene/6.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog7", "Resources/Sounds/StoryScene/7.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog8", "Resources/Sounds/StoryScene/8.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog9", "Resources/Sounds/StoryScene/9.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog10", "Resources/Sounds/StoryScene/10.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog11", "Resources/Sounds/StoryScene/11.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog12", "Resources/Sounds/StoryScene/12.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog13", "Resources/Sounds/StoryScene/13.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog14", "Resources/Sounds/StoryScene/14.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog15", "Resources/Sounds/StoryScene/15.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog16", "Resources/Sounds/StoryScene/16.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog17", "Resources/Sounds/StoryScene/17.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog18", "Resources/Sounds/StoryScene/18.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog19", "Resources/Sounds/StoryScene/19.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog20", "Resources/Sounds/StoryScene/20.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog21", "Resources/Sounds/StoryScene/21.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog22", "Resources/Sounds/StoryScene/22.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog23", "Resources/Sounds/StoryScene/23.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog24", "Resources/Sounds/StoryScene/24.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog25", "Resources/Sounds/StoryScene/25.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog26", "Resources/Sounds/StoryScene/26.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog27", "Resources/Sounds/StoryScene/27.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog28", "Resources/Sounds/StoryScene/28.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog29", "Resources/Sounds/StoryScene/29.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog30", "Resources/Sounds/StoryScene/30.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog31", "Resources/Sounds/StoryScene/31.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog32", "Resources/Sounds/StoryScene/32.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog33", "Resources/Sounds/StoryScene/33.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog34", "Resources/Sounds/StoryScene/34.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog35", "Resources/Sounds/StoryScene/35.mp3");
	SOUNDMANAGER->addSoundFMOD("Dialog36", "Resources/Sounds/StoryScene/36.mp3");
	SOUNDMANAGER->addSoundFMOD("Fight", "Resources/Sounds/StoryScene/Fight.wav");
	SOUNDMANAGER->addSoundFMOD("Scream1", "Resources/Sounds/StoryScene/Scream1.wav");
	SOUNDMANAGER->addSoundFMOD("Scream2", "Resources/Sounds/StoryScene/Scream2.wav");
	SOUNDMANAGER->addSoundFMOD("BossBattle", "Resources/Sounds/BossBattle/BossBattle.mp3", true);
	SOUNDMANAGER->addSoundFMOD("StageClear", "Resources/Sounds/BossBattle/StageClear.mp3");
	SOUNDMANAGER->addSoundFMOD("Conspiracy2", "Resources/Sounds/StoryScene/Conspiracy2.mp3", true);
	SOUNDMANAGER->addSoundFMOD("BeforeLastBattle", "Resources/Sounds/StoryScene/BeforeLastBattle.mp3", true);
	SOUNDMANAGER->addSoundFMOD("SherazadeDead", "Resources/Sounds/StoryScene/SherazadeDead.mp3");
	SOUNDMANAGER->addSoundFMOD("WorldMapBG", "Resources/Sounds/WorldMapScene/WorldMapBG.mp3", true);
	SOUNDMANAGER->addSoundFMOD("ShopSceneBG", "Resources/Sounds/ShopScene/ShopSceneBG.mp3", true);
	SOUNDMANAGER->addSoundFMOD("BattleSceneBG1", "Resources/Sounds/BattleScene/BattleSceneBG1.mp3", true);
	SOUNDMANAGER->addSoundFMOD("BattleSceneBG2", "Resources/Sounds/BattleScene/BattleSceneBG2.mp3", true);
	SOUNDMANAGER->addSoundFMOD("Bang", "Resources/Sounds/SoundEffect/Bang.wav");
	SOUNDMANAGER->addSoundFMOD("Thrust", "Resources/Sounds/SoundEffect/Thrust.wav");
	SOUNDMANAGER->addSoundFMOD("Fire", "Resources/Sounds/SoundEffect/Fire.wav");
	return S_OK;
}

void Resources::release(void)
{
}
